name: Run Playwright Instagram Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Use a versão Node.js desejada

    - name: Install dependencies
      run: |
        npx playwright install
        npm install playwright
        npm install axios

    - name: Run Playwright Instagram automation
      run: node gkzx7_.js
